server:
  port: 80
spring:
  profiles:
    active: local
  #mvc:
    #throw-exception-if-no-handler-found: true
    #dispatch-options-request: false
  #web:
    #resources:
      #add-mappings: false

logging:
  file: ./log
  config: classpath:logback-spring.xml
