spring:
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:test
      username: sa
      password: null
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
    generate-ddl: true
spring-doc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    enabled: true
tensing:
  jwt:
    tokenName: Authorization
    secretKey: Q4NSl604sgydJj1awEkR3ycUeR4uUAt7WJraD7EN3O9DVM4yyYuHxMEbSf4XXyYJkal13eqgB0F5Bqaa
    expirationInMs: 1296000000 # 1000 * 60 * 60 * 24 * 30
    signatureAlgorithm: HS512