server:
  port: 80
#server.servlet.context-path= /
spring:
  profiles:
    active: local
  #mvc:
    #throw-exception-if-no-handler-found: true
    #dispatch-options-request: false
  #web:
    #resources:
      #add-mappings: false
logging:
  file: ./log
  charset:
    console: UTF-8
  config: classpath:logback-spring.xml